### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by Integral-Tech** [lollipopkit/flutter_server_box#381] opened 2024-06-10 09:36 UTC
It would be better if ServerBox is submitted to F-Droid.

**Comment by lollipopkit** [comment] 2024-06-10 16:48
That's a good idea. Could you please help me submit this app to F-Droid, or should I do it myself?

**Comment by lollipopkit** [comment] 2024-06-11 07:51
Thank you for your efforts. :)
I have read the doc and it states that a Fastlane config should be created inside this repo.
I would like to get more people to contribute, so could you open a PR for that?

**Comment by Integral-Tech** [comment] 2024-06-11 08:11
> Thank you for your efforts. :) I have read the doc and it states that a Fastlane config should be created inside this repo. I would like to get more people to contribute, so could you open a PR for that?

Yes, I have opened a [pull request](https://github.com/lollipopkit/flutter_server_box/pull/384)

**Comment by Integral-Tech** [comment] 2024-06-11 08:20
In the [RFP issue](https://gitlab.com/fdroid/rfp/-/issues/2780), the bot detected non-free dependencies (seems to be GMS-related), which should be removed:
- com.google.android.c2dm.permission.RECEIVE

There are also some dependencies / services that could be used to track users, which should be minimized: 
- ly.count.android.sdk.messaging.CountlyPushActivity
- ly.count.android.sdk.ReferrerReceiver
- https://firebase.google.com/support/privacy/init-options
- https://plus.google.com/

**Comment by lollipopkit** [comment] 2024-06-11 08:20
It's related to #379, i will solve it later.

**Comment by licaon-kter** [comment] 2024-06-11 11:55
trying to build https://github.com/lollipopkit/flutter_server_box/commit/64ce3638cb8942499800875876d3a6fbe657516d

these proprietary libs are still pulled in via https://github.com/Countly/countly-sdk-flutter-bridge/blob/24.4.1/android/build.gradle#L38 and https://github.com/Rexios80/watch_connectivity/blob/watch_connectivity-0.2.0/watch_connectivity/android/build.gradle#L52

**Comment by lollipopkit** [comment] 2024-06-11 12:07
> trying to build [64ce363](https://github.com/lollipopkit/flutter_server_box/commit/64ce3638cb8942499800875876d3a6fbe657516d)
> 
> these proprietary libs are still pulled in via https://github.com/Countly/countly-sdk-flutter-bridge/blob/24.4.1/android/build.gradle#L38 and https://github.com/Rexios80/watch_connectivity/blob/watch_connectivity-0.2.0/watch_connectivity/android/build.gradle#L52

Thanks for the tip.

**Comment by licaon-kter** [comment] 2024-06-11 15:47
rebuilt from 5059872c3f7343054b702de8b629d53b303a8aad

```
2024-06-11 15:30:19,612 INFO: Successfully built version 1.0.963 of tech.lolli.toolbox from 5059872c3f7343054b702de8b629d53b303a8aad
2024-06-11 15:30:29,778 DEBUG: Checking build/tech.lolli.toolbox/build/app/outputs/flutter-apk/app-release.apk
2024-06-11 15:30:29,835 INFO: Scanning APK with dexdump for known non-free classes.
2024-06-11 15:30:29,951 DEBUG: > /opt/android-sdk/build-tools/33.0.0/dexdump /tmp/tmp2z8b7fta/classes.dex
2024-06-11 15:30:35,878 DEBUG: Problem: found class 'com/google/android/play/core/splitinstall/SplitInstallSessionState'
2024-06-11 15:30:35,901 DEBUG: Problem: found class 'com/google/android/play/core/splitinstall/SplitInstallStateUpdatedListener'
2024-06-11 15:30:35,927 DEBUG: Problem: found class 'com/google/android/play/core/tasks/OnSuccessListener'
2024-06-11 15:30:35,947 DEBUG: Problem: found class 'com/google/android/play/core/tasks/OnFailureListener'
2024-06-11 15:30:35,952 DEBUG: Problem: found class 'com/google/android/play/core/splitcompat/SplitCompatApplication'
2024-06-11 15:30:36,105 DEBUG: Problem: found class 'com/google/android/play/core/splitinstall/SplitInstallManager'
2024-06-11 15:30:36,118 CRITICAL: Found 6 problems in build/tech.lolli.toolbox/build/app/outputs/flutter-apk/app-release.apk
2024-06-11 15:30:36,120 ERROR: Could not build app tech.lolli.toolbox: Found blocklisted packages in final apk!
2024-06-11 15:30:36,120 DEBUG: Error encountered, stopping by user request.
```

which looks like a flutter bug https://gitlab.com/fdroid/fdroiddata/-/issues/2949

**Comment by Integral-Tech** [comment] 2024-06-11 16:52
> rebuilt from [5059872](https://github.com/lollipopkit/flutter_server_box/commit/5059872c3f7343054b702de8b629d53b303a8aad)
> 
> ```
> 2024-06-11 15:30:19,612 INFO: Successfully built version 1.0.963 of tech.lolli.toolbox from 5059872c3f7343054b702de8b629d53b303a8aad
> 2024-06-11 15:30:29,778 DEBUG: Checking build/tech.lolli.toolbox/build/app/outputs/flutter-apk/app-release.apk
> 2024-06-11 15:30:29,835 INFO: Scanning APK with dexdump for known non-free classes.
> 2024-06-11 15:30:29,951 DEBUG: > /opt/android-sdk/build-tools/33.0.0/dexdump /tmp/tmp2z8b7fta/classes.dex
> 2024-06-11 15:30:35,878 DEBUG: Problem: found class 'com/google/android/play/core/splitinstall/SplitInstallSessionState'
> 2024-06-11 15:30:35,901 DEBUG: Problem: found class 'com/google/android/play/core/splitinstall/SplitInstallStateUpdatedListener'
> 2024-06-11 15:30:35,927 DEBUG: Problem: found class 'com/google/android/play/core/tasks/OnSuccessListener'
> 2024-06-11 15:30:35,947 DEBUG: Problem: found class 'com/google/android/play/core/tasks/OnFailureListener'
> 2024-06-11 15:30:35,952 DEBUG: Problem: found class 'com/google/android/play/core/splitcompat/SplitCompatApplication'
> 2024-06-11 15:30:36,105 DEBUG: Problem: found class 'com/google/android/play/core/splitinstall/SplitInstallManager'
> 2024-06-11 15:30:36,118 CRITICAL: Found 6 problems in build/tech.lolli.toolbox/build/app/outputs/flutter-apk/app-release.apk
> 2024-06-11 15:30:36,120 ERROR: Could not build app tech.lolli.toolbox: Found blocklisted packages in final apk!
> 2024-06-11 15:30:36,120 DEBUG: Error encountered, stopping by user request.
> ```
> 
> which looks like a flutter bug https://gitlab.com/fdroid/fdroiddata/-/issues/2949

But there are some Flutter apps submitted successfully to F-Droid, such as FluffyChat

**Comment by licaon-kter** [comment] 2024-06-11 17:06
Not sure what's their magic sauce :(

**Comment by linsui** [comment] 2024-06-11 17:18
FluffyChat emptied their proguard-rules.pro.

**Comment by Integral-Tech** [comment] 2024-06-11 18:05
> > rebuilt from [5059872](https://github.com/lollipopkit/flutter_server_box/commit/5059872c3f7343054b702de8b629d53b303a8aad)
> > ```
> > 2024-06-11 15:30:19,612 INFO: Successfully built version 1.0.963 of tech.lolli.toolbox from 5059872c3f7343054b702de8b629d53b303a8aad
> > 2024-06-11 15:30:29,778 DEBUG: Checking build/tech.lolli.toolbox/build/app/outputs/flutter-apk/app-release.apk
> > 2024-06-11 15:30:29,835 INFO: Scanning APK with dexdump for known non-free classes.
> > 2024-06-11 15:30:29,951 DEBUG: > /opt/android-sdk/build-tools/33.0.0/dexdump /tmp/tmp2z8b7fta/classes.dex
> > 2024-06-11 15:30:35,878 DEBUG: Problem: found class 'com/google/android/play/core/splitinstall/SplitInstallSessionState'
> > 2024-06-11 15:30:35,901 DEBUG: Problem: found class 'com/google/android/play/core/splitinstall/SplitInstallStateUpdatedListener'
> > 2024-06-11 15:30:35,927 DEBUG: Problem: found class 'com/google/android/play/core/tasks/OnSuccessListener'
> > 2024-06-11 15:30:35,947 DEBUG: Problem: found class 'com/google/android/play/core/tasks/OnFailureListener'
> > 2024-06-11 15:30:35,952 DEBUG: Problem: found class 'com/google/android/play/core/splitcompat/SplitCompatApplication'
> > 2024-06-11 15:30:36,105 DEBUG: Problem: found class 'com/google/android/play/core/splitinstall/SplitInstallManager'
> > 2024-06-11 15:30:36,118 CRITICAL: Found 6 problems in build/tech.lolli.toolbox/build/app/outputs/flutter-apk/app-release.apk
> > 2024-06-11 15:30:36,120 ERROR: Could not build app tech.lolli.toolbox: Found blocklisted packages in final apk!
> > 2024-06-11 15:30:36,120 DEBUG: Error encountered, stopping by user request.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which looks like a flutter bug https://gitlab.com/fdroid/fdroiddata/-/issues/2949
> 
> But there are some Flutter apps submitted successfully to F-Droid, such as FluffyChat. How did they solve this problem?

I have cleaned proguard-rules.pro. Try to rebuild it :)

**Comment by Integral-Tech** [comment] 2024-06-11 18:06
@licaon-kter I have cleaned proguard-rules.pro. Try to rebuild it :)

**Comment by licaon-kter** [comment] 2024-06-12 10:19
Builds fine now

@lollipopkit up next, setup Flutter as a submodule (and use it yourself in your CI and build recipes) or at least have the exact version written somewhere

tag and build the APK from the tagged commit so we can test for reproducibility (ref: https://f-droid.org/docs/Inclusion_How-To/#reproducible-builds and https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html)

**Comment by lollipopkit** [comment] 2024-06-12 11:32
> @lollipopkit up next, setup Flutter as a submodule (and use it yourself in your CI and build recipes) or at least have the exact version written somewhere

Thanks, i have two question:
- After read the ref, I can’t figure out where(`exact version written somewhere`) to specify the Flutter version. Is it in `pubspec.yaml`? If possible, use the latest stable release of Flutter.
- If fdroid builds with my sign key, must I write the plain passwd to metadata?

**Comment by linsui** [comment] 2024-06-12 11:35
> If possible, use the latest stable release of Flutter.

We need to pin the version. The latest stable release is changing.

> If fdroid builds with my sign key, must I write the plain passwd to metadata?

We don't need your key. Do not send your key to anyone. :)

**Comment by linsui** [comment] 2024-06-12 11:36
For example, there is the revision of the flutter in https://github.com/lollipopkit/flutter_server_box/blob/main/.metadata. If you keep the file up-to-date we can use the revision specified there.

**Comment by licaon-kter** [comment] 2024-06-12 11:37
> After read the ref, I can’t figure out where(exact version written somewhere) to specify the Flutter version. Is it in pubspec.yaml? 

Where you want, eg. some use the CI, say put it here: https://github.com/lollipopkit/flutter_server_box/blob/main/.github/workflows/release.yml#L52 but not `stable` but `3.22.1`

> We need to pin the version. The latest stable release is changing.

yes, eg. yesterday was `3.22.1` you tagged (example) a version and built it

F-Droid builds today, and today... surprise `3.22.2` is stable. Maybe it's not an issue between `.1` and `.2` but there are issues between major versions

**Comment by licaon-kter** [comment] 2024-06-12 11:38
> We don't need your key. Do not send your key to anyone.

exactly, do read those two links :smile:

**Comment by lollipopkit** [comment] 2024-06-12 11:40
Thank you. I understand.

I still have questions about how to build with my sign key (if possible)? Or to release with fdroid signature (only in fdroid)?

**Comment by linsui** [comment] 2024-06-12 11:45
We only use your signature if we can make the build reproducible. See https://f-droid.org/docs/Reproducible_Builds/.

**Comment by licaon-kter** [comment] 2024-06-12 11:46
You already host apks like: https://github.com/lollipopkit/flutter_server_box/releases/tag/v1.0.949

```
$ apksigner verify --print-certs ServerBox_949_amd64.apk
Signer #1 certificate DN: CN=JunyuanFeng, OU=ToastStudio, O=ToastStudio, L=ChengDu, ST=Sichuan, C=86
```

so.. you're already setup, build and sign as usual

**Comment by lollipopkit** [comment] 2024-06-12 11:49
Sorry... I thought the apk released in fdroid would be built in fdroid ci, so was wondering how to sign it.

**Comment by licaon-kter** [comment] 2024-06-12 11:51
@lollipopkit look at the graph https://f-droid.org/docs/Reproducible_Builds/ it's YES and YES and ends up with _"publish @lollipopkit's APK"_ and not "sign something"

**Comment by lollipopkit** [comment] 2024-06-12 11:58
It's my problem...  
Before you explained it, i thought `build reproducible` could only be fdroid ci

Now the flutter version is specified in the `.github/workflows/release.yml`

**Comment by licaon-kter** [comment] 2024-06-12 15:02
is there a reason why the Tag name and the versionName don't match? https://github.com/lollipopkit/flutter_server_box/blob/v1.0.967/pubspec.yaml#L4

**Comment by lollipopkit** [comment] 2024-06-12 15:18
The version in `pubspec.yaml` is generated by a script before pushing, but the version in the tag is generated by CI after pushing. So there is a discrepancy.

Is this important? Should I fix it?

**Comment by linsui** [comment] 2024-06-12 15:45
Yes, it's important because we need a correct tag name to get your apk.

**Comment by licaon-kter** [comment] 2024-06-12 15:59
eg: `https://github.com/lollipopkit/flutter_server_box/releases/download/v1.0.967/ServerBox_967_amd64.apk`

we can use versionCode and versionName as templates for your APK url

say `https://github.com/lollipopkit/flutter_server_box/releases/download/v%v/ServerBox_%c_amd64.apk`

but... if those do not match yours Tag and are +1 we can't

**Comment by licaon-kter** [comment] 2024-06-12 16:09
regarding versionCode of the per arch APKs, please move the arch number at the end so instead of the current 1967/2967/4967 it's better to have 9671/9672/9674

it used to be here https://github.com/flutter/flutter/blob/40e3489254b2d0ffedf840bd9233e5e6d06d09dd/packages/flutter_tools/gradle/flutter.gradle#L749 kinda so instead of `abiVersionCode * 1000 + variant.versionCode` have it `variant.versionCode * 10 + abiVersionCode`

not sure where this was moved in 3.22.x

**Comment by Integral-Tech** [comment] 2024-06-12 16:22
> regarding versionCode of the per arch APKs, please move the arch number at the end so instead of the current 1967/2967/4967 it's better to have 9671/9672/9674
> 
> it used to be here https://github.com/flutter/flutter/blob/40e3489254b2d0ffedf840bd9233e5e6d06d09dd/packages/flutter_tools/gradle/flutter.gradle#L749 kinda so instead of `abiVersionCode * 1000 + variant.versionCode` have it `variant.versionCode * 10 + abiVersionCode`
> 
> not sure where this was moved in 3.22.x

I try to fix this in https://github.com/lollipopkit/flutter_server_box/pull/391, but I am not sure if my fix is correct

**Comment by lollipopkit** [comment] 2024-06-12 16:54
v1.0.971 solved these two.

**Comment by licaon-kter** [comment] 2024-06-13 09:44
Ok, builds, some notes:
* the APK names, since versionCode is different per arch, maybe name them based on that instead being `971`, as they are `9713` `9711` etc, or better yet just remove the `971`
* it's almost repro, here's the diff log: [tech9713.log.7z.zip](https://github.com/user-attachments/files/15817232/tech9713.log.7z.zip) _(remove `.ZIP` from filename)_


@linsui this diff looks familiar?

**Comment by linsui** [comment] 2024-06-13 10:42
No. @lollipopkit Can you explain how you build your apk?

**Comment by lollipopkit** [comment] 2024-06-13 11:00
I built the apks as shown in Actions.

The reason why this diff occurs, may due to (i guess):

Zulu jdk17:https://github.com/lollipopkit/flutter_server_box/blob/108d0a5a5b4a6889ffbc801df4a95142910c49d2/.github/workflows/release.yml#L27
My custom build script: https://github.com/lollipopkit/flutter_server_box/blob/108d0a5a5b4a6889ffbc801df4a95142910c49d2/.github/workflows/release.yml#L34

**Comment by linsui** [comment] 2024-06-13 11:40
I want to know what your script does. :) Can we also run

```
dart run fl_build -p android
```

to build the apk?

**Comment by lollipopkit** [comment] 2024-06-13 11:43
Yes, `dart run` runs a pkg(bin) named `fl_build`, it can be found at: 
https://github.com/lollipopkit/flutter_server_box/blob/108d0a5a5b4a6889ffbc801df4a95142910c49d2/pubspec.yaml#L79

**Comment by linsui** [comment] 2024-06-13 11:51
Does it do anything special? How can I build only 1 abi with it?

**Comment by lollipopkit** [comment] 2024-06-13 11:58
It updates metadata used by update checker and others. 
It can't build 1 abi...

I think just use zulu to build, then the diff will decrease much.

**Comment by linsui** [comment] 2024-06-13 12:03
Zulu is only used to build the java part but the libapp.so has difference. The `BuildData.build` is different. In your apk it's 971 and in our apk it's 970.

**Comment by lollipopkit** [comment] 2024-06-13 12:04
Ok, i will update it to support only 1 abi.

**Comment by lollipopkit** [comment] 2024-06-13 12:07
But it can't completely repro.

The `buildAt` vary every build time.
https://github.com/lollipopkit/flutter_server_box/blob/108d0a5a5b4a6889ffbc801df4a95142910c49d2/lib/data/res/build_data.dart#L7

**Comment by linsui** [comment] 2024-06-13 12:07
Why is https://github.com/lollipopkit/flutter_server_box/blob/v1.0.971/lib/data/res/build_data.dart not updated to 971? Does your script update it when building the apk?

**Comment by lollipopkit** [comment] 2024-06-13 12:07
> Does your script update it when building the apk?

**Comment by linsui** [comment] 2024-06-13 12:09
That's the problem... We need to build the apk from the same code. If it update the code everytime we can't get the same apk.

**Comment by lollipopkit** [comment] 2024-06-13 12:11
Can i delete `buildAt` but leave `build`?

**Comment by linsui** [comment] 2024-06-13 12:14
I thought it should work.

**Comment by lollipopkit** [comment] 2024-06-13 12:29
Now the build script will output apk at `build/app/outputs/flutter-apk/app-release.apk`

**Comment by linsui** [comment] 2024-06-13 12:37
How should we build, e.g., an arm64 apk with fl_build?

**Comment by lollipopkit** [comment] 2024-06-13 12:40
`dart run fl_build -p android -ooa`

**Comment by linsui** [comment] 2024-06-13 12:41
How can I tell it which abi should be built?

**Comment by lollipopkit** [comment] 2024-06-13 12:44
Is the versionCode in app name makes your script harder to write?

**Comment by linsui** [comment] 2024-06-13 12:45
Since you publish 3 abis on GitHub...

**Comment by lollipopkit** [comment] 2024-06-13 12:48
fl_build without `-ooa` behaves as `--split-per-abi`, with 3 abis...
So i guess that you only need arm64 one...

> Is the versionCode in app name makes your script harder to write?
If this matters you, i can delete the versionCode from app name.

**Comment by licaon-kter** [comment] 2024-06-13 12:55
> So i guess that you only need arm64 one...

we need all 3, I mean not us... but users... users of arm need arm, users of amd64 need that

> fl_build without -ooa behaves as --split-per-abi, with 3 abis...

so all 3 are created? we can use that, brb

**Comment by lollipopkit** [comment] 2024-06-13 13:02
Output format is the same as Actions assets.
<img width="211" alt="image" src="https://github.com/lollipopkit/flutter_server_box/assets/10864310/cd6fbc1e-746a-40e0-a136-96b15472d2af">

**Comment by linsui** [comment] 2024-06-13 13:12
> so all 3 are created? we can use that, brb

Then every apk takes longer to build. So can you add an argument so that we can build the specified abi?

**Comment by lollipopkit** [comment] 2024-06-13 13:13
ok

**Comment by licaon-kter** [comment] 2024-06-13 13:23
```
+ dart run fl_build -p android
GITHUB_ENV is not set. Skip writing env.
Running beforeBuild...

Unhandled exception:
PathNotFoundException: Cannot open file, path = 'ios/Runner.xcodeproj/project.pbxproj' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
<asynchronous suspension>
#2      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562:24)
<asynchronous suspension>
#3      _File.readAsString (dart:io/file_impl.dart:621:18)
<asynchronous suspension>
#4      changeAppleVersion (package:fl_build/utils.dart:52:22)
<asynchronous suspension>
#5      main (file:///home/runner/work/flutter_server_box/flutter_server_box/.pub-cache/git/fl_build-9d5c990c66ce7d7448f4580ae832c93b3cf11314/bin/fl_build.dart:64:3)
<asynchronous suspension>
```

can you untangle the need for the `ios` folder when building for android?

**Comment by lollipopkit** [comment] 2024-06-13 13:24
ok

**Comment by lollipopkit** [comment] 2024-06-13 13:34
Done.
Should i trigger the ci?

**Comment by lollipopkit** [comment] 2024-06-13 14:17
I decided to put the metadata update logic before the commit, otherwise it's too coupled...
So just use your scripts.

**Comment by licaon-kter** [comment] 2024-06-13 14:31
waiting on the tag to test :+1:

**Comment by licaon-kter** [comment] 2024-06-13 14:57
APK name is still wacky :stuck_out_tongue:

**Comment by lollipopkit** [comment] 2024-06-13 14:59
fmt like `ServerBox_arm64.apk` is ok?

**Comment by lollipopkit** [comment] 2024-06-13 15:00
I want to keep versionCode in app name if possible...

**Comment by licaon-kter** [comment] 2024-06-13 15:06
you can't put **the real versionCode** in name?

Ignoring the fact that tag is 976 and in name you've put 977, the real number is 9671...2...3... right?

**Comment by lollipopkit** [comment] 2024-06-13 15:59
977 uses versionName

**Comment by licaon-kter** [comment] 2024-06-17 09:39
There are 2 hard problems in computing
1. naming things
2. cache invalidation
3. counting

```
ERROR: Could not build app tech.lolli.toolbox: Unexpected version/version code in output; APK: '1.0.978' / '9783',  Expected: '1.0.977' / '9773'
``` @ 161f536a625e5879145044af7fb2aa2ea79285ef

**Comment by licaon-kter** [comment] 2024-06-17 13:01
Interesting enough build log says:
```
2024-06-17 12:52:12,375 DEBUG: buildserver > + dart run fl_build -p android
2024-06-17 12:52:13,781 DEBUG: buildserver > GITHUB_ENV is not set. Skip writing env.
2024-06-17 12:52:13,781 DEBUG: buildserver > Running beforeBuild...
2024-06-17 12:52:18,502 DEBUG: buildserver > 
2024-06-17 12:52:18,502 DEBUG: buildserver > 
2024-06-17 12:52:18,503 DEBUG: buildserver > [apk]
2024-06-17 12:52:18,503 DEBUG: buildserver > flutter build apk --build-number=978 --build-name=1.0.978 --split-per-abi
```

I see `977` here https://github.com/lollipopkit/flutter_server_box/blob/v1.0.977/lib/data/res/build_data.dart#L5 though....

**Comment by lollipopkit** [comment] 2024-06-17 13:06
[issuecomment-2165810357](https://github.com/lollipopkit/flutter_server_box/issues/381#issuecomment-2165810357)

Use your build script instead of `fl_build` in order to decouple these logics.

**Comment by licaon-kter** [comment] 2024-06-17 14:13
@lollipopkit yup, I've read it backwards :stuck_out_tongue:

**Comment by licaon-kter** [comment] 2024-06-17 14:34
Wasn't this a client for my own servers? Why does it connect to `cdn.lolli.tech` at start? ref: https://github.com/lollipopkit/flutter_server_box/blob/v1.0.977/lib/data/res/url.dart#L2

**Comment by linsui** [comment] 2024-06-17 14:38
It's for auto update. Auto update should be opt-in.

**Comment by lollipopkit** [comment] 2024-06-17 14:59
It's update checker url. There is a switch in settings, you can turn it off.

**Comment by licaon-kter** [comment] 2024-06-17 15:02
It needs to be off by default, specially for reproducible builds.

**Comment by lollipopkit** [comment] 2024-06-18 05:34
Can i add a mark (such as `//FOR_FDROID`) at line end:
https://github.com/lollipopkit/flutter_server_box/blob/161f536a625e5879145044af7fb2aa2ea79285ef/lib/data/store/setting.dart#L151

And you replace it to false in your script?

**Comment by licaon-kter** [comment] 2024-06-18 05:52
How would the APK then be reproducible if the source is different?

**Comment by lollipopkit** [comment] 2024-06-18 05:55
...Add an intro screen at first launch for this settings setup?

**Comment by linsui** [comment] 2024-06-18 06:19
That would be good. :)

**Comment by Integral-Tech** [comment] 2024-06-18 06:23
> It needs to be off by default, specially for reproducible builds.

Is it because the apk published by F-Droid has different signature from apk downloaded from GitHub Release?

**Comment by linsui** [comment] 2024-06-18 06:30
It has the same signaure. But some users don't understand where the update is from. If the auto update is on by default, the user may switch to upstream channel without noticing that. And upstream devs may add non-free deps by mistake and push the update to users directly before F-Droid can check that.

**Comment by licaon-kter** [comment] 2024-06-18 06:58
> Add an intro screen at first launch for this settings setup?

...that explains that the update is from  the developer

@Integral-Tech two ideas
* as said above, expectations, users wanted the app _"built and **verified** by F-Droid"_
* if on by default means we need to add **NonFreeNet** and **Tracking** anti-features to the app, ref: https://f-droid.org/docs/Anti-Features/

**Comment by Integral-Tech** [comment] 2024-06-18 07:07
> > Add an intro screen at first launch for this settings setup?
> 
> ...that explains that the update is from the developer
> 
> @Integral-Tech two ideas
> 
>     * as said above, expectations, users wanted the app _"built and **verified** by F-Droid"_
> 
>     * if on by default means we need to add **NonFreeNet** and **Tracking** anti-features to the app, ref: https://f-droid.org/docs/Anti-Features/  (but the point above has priority anyway)

Okay, I see

**Comment by lollipopkit** [comment] 2024-06-24 03:38
Sorry for late.

Is this okay?

<img width=200 src="https://github.com/lollipopkit/flutter_server_box/assets/10864310/f40b9f38-0b45-4729-9312-b3d513245dfc"/>

**Comment by linsui** [comment] 2024-06-24 07:22
Looks good to me. :)

**Comment by licaon-kter** [comment] 2024-06-25 13:31
for the next version do correct the typo https://github.com/lollipopkit/flutter_server_box/blob/v1.0.992/lib/l10n/app_en.arb#L104 it's `F-Droid` :wink:

**Comment by licaon-kter** [comment] 2024-06-25 14:54
merged https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15273 :tada: 

@lollipopkit fyi https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

**Comment by lollipopkit** [comment] 2024-06-25 15:39
Thanks for your help.
🥳

**Closed** 2024-06-26 07:21 UTC
