### ISSUE TITLE
Adding a new server with same ip create some issue

### ISSUE THREAD

**Issue by Darkmagister** [lollipopkit/flutter_server_box#581] opened 2024-09-20 08:20 UTC
**Describe the bug**

I've added the same server 2 time my idea was testing with different user, but I noticed that when I have two, if I edit one the other edit too, and if I remove one, the other disappear, but if I add it again I see 2 again, I can not remove it now (only solution was removing and reinstalling the app)

**To Reproduce**

Create one server, then create another one with the same ip, now the edit ore removing is not possible for both indioendently

**Desired Results**

**Actual Results**

**Screenshots**

**Device**

Xiaomi 14
Android 14
App 1.0.1070

**Additional context**

**Comment by lollipopkit** [comment] 2024-09-21 03:46
Can't reproduce, maybe a Heisenbug

https://github.com/user-attachments/assets/faad2d30-15e0-42ed-8d6f-b080ef1e2834

**Comment by lollipopkit** [comment] 2024-09-21 03:55
a related pr merged: #585

**Comment by Darkmagister** [comment] 2024-09-21 09:00
I've tried again and now it doesn't show .... I'm sorry I don't know why... I tried to reproduce it but now it working ok I don't know what I did to make that happen then

**Comment by lollipopkit** [comment] 2024-09-21 09:03
Doesn't matter, just feedback next time you encounter it~

**Closed** 2024-09-21 09:04 UTC
